name: Deploy to Subdomain

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Vue.js project
        run: |
          npm install
          npm run build

      - name: Move dist files to root
        run: mv dist/* ./

      - name: Deploy to Subdomain
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4

        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          passive: true
